name: dishpatch-control-backend

services:
  backend:
    container_name: dishpatch-control-backend
    image: dishpatch-control-backend:latest

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      SERVER_PORT: "8081"
      SERVER_ADDRESS: "0.0.0.0"
      CONTROL_BACKEND_USERS_TABLE: "Users"

    expose:
      - "8081"

    networks:
      dishpatch-shared:
        aliases:
          - dishpatch-backend

networks:
  dishpatch-shared:
    external: true
    name: "${DISH_PATCH_NETWORK_NAME:-dishpatch-network}"