"""
multi_nav2_launch.py — Launch minimal Nav2 stack for multiple robot namespaces.

Replicates the original per-robot Nav2 setup (5 nodes: map_server,
planner_server, controller_server, bt_navigator, lifecycle_manager) — but
parameterized by a comma-separated list of namespaces so a single Nav2
container can serve the whole fleet.

Usage:
  ros2 launch nav2_launcher multi_nav2_launch.py namespaces:=robot1,robot2

Params file is expected at /tmp/nav2_params_<ns>.yaml (generated by
nav2_entrypoint.sh from /ros2_ws/config/nav2_params_template.yaml).

Alongside the Nav2 five, each namespace also gets a costmap_z_offset_node — see
the costmap_viz package for why the local costmap has to be republished before
Foxglove can draw it and the map at the same time.
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _build_nav2_nodes(ns: str, costmap_z_offset: str):
    params_file = f"/tmp/nav2_params_{ns}.yaml"

    map_server = Node(
        package="nav2_map_server",
        executable="map_server",
        name="map_server",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    planner_server = Node(
        package="nav2_planner",
        executable="planner_server",
        name="planner_server",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    controller_server = Node(
        package="nav2_controller",
        executable="controller_server",
        name="controller_server",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    bt_navigator = Node(
        package="nav2_bt_navigator",
        executable="bt_navigator",
        name="bt_navigator",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    lifecycle_manager = Node(
        package="nav2_lifecycle_manager",
        executable="lifecycle_manager",
        name="lifecycle_manager",
        namespace=ns,
        parameters=[
            params_file,
            {
                "autostart": True,
                "node_names": [
                    "map_server",
                    "planner_server",
                    "controller_server",
                    "bt_navigator",
                ],
            },
        ],
        output="screen",
    )

    # Not a lifecycle node, so deliberately absent from lifecycle_manager's
    # node_names above — listing it there would leave the manager waiting
    # forever for a state transition it can never make, and the four real Nav2
    # nodes never come up.
    costmap_z_offset_node = Node(
        package="costmap_viz",
        executable="costmap_z_offset_node",
        name="costmap_z_offset_node",
        namespace=ns,
        parameters=[{"z_offset": float(costmap_z_offset)}],
        output="screen",
    )

    return [
        map_server,
        planner_server,
        controller_server,
        bt_navigator,
        lifecycle_manager,
        costmap_z_offset_node,
    ]


def _spawn_for_each_namespace(context, *args, **kwargs):
    ns_csv = LaunchConfiguration("namespaces").perform(context)
    costmap_z_offset = LaunchConfiguration("costmap_z_offset").perform(context)
    nodes = []
    for ns in [n.strip() for n in ns_csv.split(",") if n.strip()]:
        nodes.extend(_build_nav2_nodes(ns, costmap_z_offset))
    return nodes


def generate_launch_description():
    namespaces_arg = DeclareLaunchArgument(
        "namespaces",
        default_value="robot1",
        description="Comma-separated robot namespaces, e.g. 'robot1,robot2'",
    )

    costmap_z_offset_arg = DeclareLaunchArgument(
        "costmap_z_offset",
        default_value="0.10",
        description="Metres to lift the republished local costmap by, so it does "
                    "not z-fight the map in a 3D view",
    )

    return LaunchDescription([
        namespaces_arg,
        costmap_z_offset_arg,
        OpaqueFunction(function=_spawn_for_each_namespace),
    ])
