"""
multi_nav2_launch.py — Launch minimal Nav2 stack for multiple robot namespaces.

Replicates the original per-robot Nav2 setup (5 nodes: map_server,
planner_server, controller_server, bt_navigator, lifecycle_manager) — but
parameterized by a comma-separated list of namespaces so a single Nav2
container can serve the whole fleet.

Usage:
  ros2 launch nav2_launcher multi_nav2_launch.py namespaces:=robot1,robot2

Params file is expected at /tmp/nav2_params_<ns>.yaml (generated by
nav2_entrypoint.sh from /ros2_ws/config/nav2_params_template.yaml).
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _build_nav2_nodes(ns: str):
    params_file = f"/tmp/nav2_params_{ns}.yaml"

    map_server = Node(
        package="nav2_map_server",
        executable="map_server",
        name="map_server",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    planner_server = Node(
        package="nav2_planner",
        executable="planner_server",
        name="planner_server",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    controller_server = Node(
        package="nav2_controller",
        executable="controller_server",
        name="controller_server",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    bt_navigator = Node(
        package="nav2_bt_navigator",
        executable="bt_navigator",
        name="bt_navigator",
        namespace=ns,
        parameters=[params_file],
        output="screen",
    )

    lifecycle_manager = Node(
        package="nav2_lifecycle_manager",
        executable="lifecycle_manager",
        name="lifecycle_manager",
        namespace=ns,
        parameters=[
            params_file,
            {
                "autostart": True,
                "node_names": [
                    "map_server",
                    "planner_server",
                    "controller_server",
                    "bt_navigator",
                ],
            },
        ],
        output="screen",
    )

    return [map_server, planner_server, controller_server, bt_navigator, lifecycle_manager]


def _spawn_for_each_namespace(context, *args, **kwargs):
    ns_csv = LaunchConfiguration("namespaces").perform(context)
    nodes = []
    for ns in [n.strip() for n in ns_csv.split(",") if n.strip()]:
        nodes.extend(_build_nav2_nodes(ns))
    return nodes


def generate_launch_description():
    namespaces_arg = DeclareLaunchArgument(
        "namespaces",
        default_value="robot1",
        description="Comma-separated robot namespaces, e.g. 'robot1,robot2'",
    )

    return LaunchDescription([
        namespaces_arg,
        OpaqueFunction(function=_spawn_for_each_namespace),
    ])
