package com.dishpatch.map;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Behaviour of {@link DropPointService}.
 *
 * Constructed directly rather than through @SpringBootTest: the full context
 * starts RosBridgeService, which opens a WebSocket to the shared rosbridge and
 * retries on a loop. These stay offline and fast.
 */
class DropPointServiceTest {

    private static DropPointService serviceFor(Resource source) {
        return new DropPointService(new ObjectMapper(), source);
    }

    private static Resource json(String body) {
        return new ByteArrayResource(body.getBytes(StandardCharsets.UTF_8));
    }

    private static String mapWith(String dropPoints) {
        return """
                {
                  "map": "m.yaml",
                  "frameId": "map",
                  "resolution": 0.011802,
                  "origin": [0.0, 0.0, 0.0],
                  "dropPoints": [%s]
                }
                """.formatted(dropPoints);
    }

    @Test
    void loadsTheStagedFileFromTheClasspath() throws IOException {
        // Guards the staging pipeline: this file is gitignored and generated by
        // map-source/stage-map-assets.sh, so a broken staging step fails here.
        DropPointService service =
                serviceFor(new ClassPathResource("drop-points.json"));
        service.load();

        assertEquals(25, service.all().size(),
                "expected 18 tables + 7 rooms; run map-source/stage-map-assets.sh");
        assertEquals("map", service.frameId());
    }

    @Test
    void everyDestinationOnTheFloorplanResolves() throws IOException {
        DropPointService service =
                serviceFor(new ClassPathResource("drop-points.json"));
        service.load();

        for (int i = 1; i <= 18; i++) {
            assertTrue(service.find("table_" + i).isPresent(), "missing table_" + i);
        }
        for (int i = 1; i <= 7; i++) {
            assertTrue(service.find("room_" + i).isPresent(), "missing room_" + i);
        }
    }

    @Test
    void findReturnsThePoseFromTheSource() throws IOException {
        DropPointService service =
                serviceFor(new ClassPathResource("drop-points.json"));
        service.load();

        DropPointMap.DropPoint point = service.find("table_4").orElseThrow();

        // Matches table_4 in the staged drop-points.json.
        assertEquals(23.226, point.x());
        assertEquals(9.241, point.y());
        assertEquals(0.0, point.yaw());
    }

    @Test
    void findIsEmptyForAnUnknownId() throws IOException {
        DropPointService service =
                serviceFor(new ClassPathResource("drop-points.json"));
        service.load();

        assertTrue(service.find("table_99").isEmpty());
        assertTrue(service.find("").isEmpty());
    }

    @Test
    void rejectsDuplicateIds() {
        Resource source = json(mapWith("""
                { "id": "table_1", "x": 1.0, "y": 2.0, "yaw": 0.0 },
                { "id": "table_1", "x": 9.0, "y": 9.0, "yaw": 0.0 }
                """));

        IllegalStateException thrown = assertThrows(
                IllegalStateException.class, serviceFor(source)::load);

        assertTrue(thrown.getMessage().contains("table_1"), thrown.getMessage());
    }

    @Test
    void failsWhenTheStagedFileIsAbsent() {
        DropPointService service =
                serviceFor(new ClassPathResource("no-such-drop-points.json"));

        // Surfaces at startup as a BeanCreationException rather than on the
        // first delivery.
        assertThrows(IOException.class, service::load);
    }

    @Test
    void keepsSourceOrderInAll() throws IOException {
        Resource source = json(mapWith("""
                { "id": "room_3", "x": 1.0, "y": 1.0, "yaw": 0.0 },
                { "id": "table_1", "x": 2.0, "y": 2.0, "yaw": 0.0 }
                """));

        DropPointService service = serviceFor(source);
        service.load();

        assertEquals("room_3", service.all().get(0).id());
        assertEquals("table_1", service.all().get(1).id());
    }
}
