"""
robot_launch.py — Bringup launch file for a single robot instance.

Usage (inside the container):
  ros2 launch robot_bringup robot_launch.py namespace:=robot1

Parameters:
  namespace       — ROS namespace prefix, e.g. "robot1"
  robot_id        — Human-readable ID, defaults to <namespace>
  initial_battery — Starting battery percentage (0-100)
  nav2_params     — Path to nav2 params YAML (generated by robot_entrypoint.sh)
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node


def generate_launch_description():
    # ── Declare arguments ──────────────────────────────────────────────
    ns_arg = DeclareLaunchArgument(
        "namespace",
        default_value="robot",
        description="Namespace for this robot (e.g. robot1, robot2)",
    )
    robot_id_arg = DeclareLaunchArgument(
        "robot_id",
        default_value=LaunchConfiguration("namespace"),
        description="Robot identifier string",
    )
    initial_battery_arg = DeclareLaunchArgument(
        "initial_battery",
        default_value="100.0",
        description="Starting battery percentage (0-100)",
    )
    nav2_params_arg = DeclareLaunchArgument(
        "nav2_params",
        default_value="/tmp/nav2_params_robot.yaml",
        description="Path to per-robot nav2 params file",
    )

    # ── Shared substitutions ───────────────────────────────────────────
    ns = LaunchConfiguration("namespace")
    robot_id = LaunchConfiguration("robot_id")
    initial_battery = LaunchConfiguration("initial_battery")
    nav2_params = LaunchConfiguration("nav2_params")

    ns_odom = PythonExpression(["'", ns, "/odom'"])
    ns_base_link = PythonExpression(["'", ns, "/base_link'"])

    # ── Custom nodes ───────────────────────────────────────────────────

    hardware_node = Node(
        package="robot_hardware",
        executable="hardware_node",
        name="hardware_node",
        namespace=ns,
        parameters=[
            {"robot_namespace": ns},
            {"robot_id": robot_id},
            {"initial_battery": initial_battery},
        ],
        output="screen",
        emulate_tty=True,
    )

    nav_node = Node(
        package="robot_navigation",
        executable="nav_node",
        name="nav_node",
        namespace=ns,
        parameters=[{"robot_namespace": ns}],
        output="screen",
        emulate_tty=True,
    )

    goal_relay_node = Node(
        package="robot_navigation",
        executable="goal_relay_node",
        name="goal_relay_node",
        namespace=ns,
        parameters=[{"robot_namespace": ns}],
        output="screen",
        emulate_tty=True,
    )

    status_node = Node(
        package="robot_status",
        executable="status_node",
        name="status_node",
        namespace=ns,
        parameters=[
            {"robot_namespace": ns},
            {"robot_id": robot_id},
        ],
        output="screen",
        emulate_tty=True,
    )

    # ── Static TF: map → {ns}/odom ────────────────────────────────────
    map_to_odom_tf = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        name="map_to_odom_tf",
        namespace=ns,
        arguments=["0", "0", "0", "0", "0", "0", "map", ns_odom],
        output="screen",
    )

    # ── Nav2 nodes ─────────────────────────────────────────────────────

    map_server = Node(
        package="nav2_map_server",
        executable="map_server",
        name="map_server",
        namespace=ns,
        parameters=[nav2_params],
        output="screen",
    )

    planner_server = Node(
        package="nav2_planner",
        executable="planner_server",
        name="planner_server",
        namespace=ns,
        parameters=[nav2_params],
        output="screen",
    )

    controller_server = Node(
        package="nav2_controller",
        executable="controller_server",
        name="controller_server",
        namespace=ns,
        parameters=[nav2_params],
        remappings=[("cmd_vel", f"cmd_vel")],
        output="screen",
    )

    bt_navigator = Node(
        package="nav2_bt_navigator",
        executable="bt_navigator",
        name="bt_navigator",
        namespace=ns,
        parameters=[nav2_params],
        output="screen",
    )

    lifecycle_manager = Node(
        package="nav2_lifecycle_manager",
        executable="lifecycle_manager",
        name="lifecycle_manager",
        namespace=ns,
        parameters=[
            nav2_params,
            {
                "autostart": True,
                "node_names": [
                    "map_server",
                    "planner_server",
                    "controller_server",
                    "bt_navigator",
                ],
            },
        ],
        output="screen",
    )

    return LaunchDescription([
        ns_arg,
        robot_id_arg,
        initial_battery_arg,
        nav2_params_arg,
        # custom nodes
        hardware_node,
        nav_node,
        goal_relay_node,
        status_node,
        # static TF
        map_to_odom_tf,
        # Nav2
        map_server,
        planner_server,
        controller_server,
        bt_navigator,
        lifecycle_manager,
    ])
